In [1]:
import numpy as np
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(mat[:,2])
print(mat[3,:])
print(mat[:,2:4])


[ 3  7 11 15]
[13 14 15 16]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
