In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,4,8,16])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(b))


[ 3  6 11 20]
[ -1  -2  -5 -12]
[ 2  8 24 64]
[0.5   0.5   0.375 0.25 ]
[ 1  4  9 16]
[1.41421356 2.         2.82842712 4.        ]
